version: "3.8"

networks:
  network:
    driver: overlay

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - network
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    networks:
      - network
    deploy:
      replicas: 2

  prueba:
    image: alejandro/prueba-service:latest
    networks:
      - network
    ports:
      - "6000:6000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  apigateway:
    image: alejandro/apigateway-service:latest
    networks:
      - network
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  payment-service:
    image: alejandro/payment-service:latest
    ports:
      - "5002:5002"
    networks:
      - network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  authorization-service:
    image: alejandro/authorization-service:latest
    networks:
      - network
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__WriteTo__1__Args__nodeUris=http://elasticsearch:9200
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  validation-service:
    image: alejandro/validation-service:latest
    ports:
      - "5003:5003"
    networks:
      - network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__WriteTo__1__Args__nodeUris=http://elasticsearch:9200
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure